import './styles/globals.css';
import { Toaster } from "react-hot-toast";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Toaster position="top-right" reverseOrder={false} />
      <body>{children}</body>
    </html>
  )
}
